name: lab2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.6.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.1
  firebase_core: ^3.8.1
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
